# YAML Configuration file for the file-mod-ai.py script

# Instructions for the AI. These instructions will be sent to the AI along with the file paths it can request.
# The AI will use these instructions to generate the modifications.
instructions: |
  Change the name of the dog to 'Chewie'.

# Source paths of the files to be processed by the AI. These files (or parts of files if using slices) will be read 
# and sent to the AI.
# Use Python slice syntax at the end of the path to specify a range of lines to read from the file.
src_paths: 
  - example.txt

use_config_for_cwd: true
